Project organizer

This project aims to set up an uniform way to manage multiple
projects, trying to support many different SCMs and modalities.


Every project can be a separate entity, but sharing configurations and
general rules with many other projects.

In case there is an original project of our personal fork, we should
be able to see detailed diffs and statistics about it.

* Git
  We can use [[https://github.com/libgit2/pygit2][libgit2]] and its python bindings to access to git
  repositories from git.

* Mercurial
  [[http://mercurial.selenic.com/wiki/MercurialApi][Official mercurial API]] to access the repository in an object
  oriented fashion.  The official API can break compatibility at every
  version, use [[https://bitbucket.org/haard/hgapi][HGapi]] to get a stable interface.

* Bazaar
  [[http://wiki.bazaar.canonical.com/BzrLib][BZrlib]]

* Subversion
  [[http://svnbook.red-bean.com/en/1.1/ch08s02.html][using the SVN api]] with some examples in Python

* To compile everything together we might need to use cmake

* Tasks
** TODO take from mr.developer or write from scratch some code to abstract the SCM used

** TODO define a grammar/syntax for a configuration file format

** TODO write doc in RST format

* Emacs integration
  Switching to project should be done withing Emacs (calling shell
  commands) too with the following:
  - always store buffers and window configurations used
  - restore buffers (maybe in new frames) and window configurations
  - show and analyse the time spent in each of the projects
    (possibly using org-mode and its advanced timing mechanisms)

  Keep a database storing all the bugs filled, and create
  org-mode-like links to be able to jump them easily.

* Ideas
  - this project might be a good candidate to test the actor model for
    some real concurrency, see for example pyzmq
  - instead of reinventing the wheel and try to create another
    SCM-agnostic generic system, just make it very easy to create
    generic alias for commonly used operations
